const { commands, bot } = require('./plugins');
const { getAntiLink, setAntiLink, deleteAntiLink, addAntiWord, removeAntiWord, getAntiWords, getAutoReactSettings, setAutoReactSettings, getFilter, setFilter, deleteFilter, getPausedChats, savePausedChat, deleteAllPausedChats, installPlugin, getandRequirePlugins, removePlugin, saveMessage, loadMessage, saveChat, getName, getWarns, saveWarn, resetWarn, setMessage, getMessage, delMessage, toggleStatus, getStatus } = require('./database');
const { handleMessages } = require('./misc/msgs');
module.exports = {
 Base: require('./_base'),
 Message: require('./_message'),
 ReplyMessage: require('./_reply'),
 getSession: require('./session'),
 GroupManager: require('./groups'),
 GreetingsHandler: require('./misc/group'),
 commands,
 bot,
 getAntiLink,
 setAntiLink,
 deleteAntiLink,
 addAntiWord,
 removeAntiWord,
 getAntiWords,
 getAutoReactSettings,
 setAutoReactSettings,
 getFilter,
 setFilter,
 deleteFilter,
 getPausedChats,
 savePausedChat,
 deleteAllPausedChats,
 installPlugin,
 getandRequirePlugins,
 removePlugin,
 saveMessage,
 loadMessage,
 saveChat,
 getName,
 getWarns,
 saveWarn,
 resetWarn,
 setMessage,
 getMessage,
 delMessage,
 toggleStatus,
 getStatus,
 handleMessages
};
